services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: logistika_frontend
    ports:
      - "127.0.0.1:8088:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
